package com.supinfo.suprails.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "TripWebService", targetNamespace = "http://webservices.suprails.supinfo.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TripWebService {


    /**
     * @return returns java.util.List<com.supinfo.suprails.webservices.Trip>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTrips", targetNamespace = "http://webservices.suprails.supinfo.com/", className = "com.supinfo.suprails.webservices.GetAllTrips")
    @ResponseWrapper(localName = "getAllTripsResponse", targetNamespace = "http://webservices.suprails.supinfo.com/", className = "com.supinfo.suprails.webservices.GetAllTripsResponse")
    @Action(input = "http://webservices.suprails.supinfo.com/TripWebService/getAllTripsRequest", output = "http://webservices.suprails.supinfo.com/TripWebService/getAllTripsResponse")
    public List<Trip> getAllTrips();

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://webservices.suprails.supinfo.com/", className = "com.supinfo.suprails.webservices.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://webservices.suprails.supinfo.com/", className = "com.supinfo.suprails.webservices.ProcessOrderResponse")
    @Action(input = "http://webservices.suprails.supinfo.com/TripWebService/processOrderRequest", output = "http://webservices.suprails.supinfo.com/TripWebService/processOrderResponse")
    public void processOrder(
            @WebParam(name = "arg0", targetNamespace = "")
            CustomerOrder arg0);

}
